# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68f1164e5ba0ee98565f7f001c8eba1f03daf92d8df2b35c199ff129e0a2120e8ce1b93cf982ac327251f45d20960bb5b8c4184dc723c8956b1331d889b53c6d

test:
  secret_key_base: 31a5bd298b6ae90293d10252a829bff954eae1acadcc7c8d7505031ed375f46f3cf66dd0f7e3505e227152dd961f42f90916461db9983517f2509ebfb384c5d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
